services:
  - type: web
    name: app-cook-backend
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main_async:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.5
      - key: PORT
        generateValue: true
    healthCheckPath: /health
